### PR TITLE
Better docs

### PR DESCRIPTION
**Pull request by thomscoder**
Alright. ( #24 )
Here we are @micheleriva 😄👋🏽 

New docs live at /packages/lyra-docs.
A simple `pnpm install` && `pnpm start` should run with no problems.

- [x] homepage 
- [x] getting started and installation
- [x] create lyra instance page
- [x] search data page
- [x] insert data page
- [x] delete data page

...some extras.

<hr>

For the [local search](https://docusaurus.io/docs/search#using-local-search) ([hope I understood correctly](https://github.com/nearform/lyra/issues/24#issuecomment-1193696436)) I used
[Local search plugin](https://github.com/cmfcmf/docusaurus-search-local), as it was the most mantained one in the [list](https://docusaurus.io/community/resources#search).

Waiting for when we'll implement Lyra as search engine 😉 
I open a draft pr because I expect some fine tuning activities and some finessing to do.

### Fine tuning and finessing

- [x] Removal of blog .md files
- [x] Removal unused images
- [x] Dead code cleaning
- [ ] Re-checking for typos
- [ ] Search bar fix

Cannot wait to hear your feedback. 👊🏽

### CODE REVIEW

**Comment by micheleriva** [comment]
Thank you so much @thomscoder , I'll review this ASAP

**Comment by micheleriva** [comment]
Is that normal? 😞 

Screenshot 2022-07-31 at 12 48 47

**Comment by thomscoder** [comment]
> Is that normal? 😞
> 
> Screenshot 2022-07-31 at 12 48 47

Absolutely not. Apparently the a fresh install of the [local search plugin](https://github.com/cmfcmf/docusaurus-search-local) made the page crash.
Removed it I am gonna investigate and most likely I'm gonna open an issue on there. 

Should be working fine now (without the search bar)

**Comment by micheleriva** [comment]
Alright! Now it's working fine 🙂

**Comment by thomscoder** [comment]
Added in the fine tuning 😄

**Comment by micheleriva** [comment]
@thomscoder LGTM! I'll merge this and make some minor edits before publishing 🙂

**Review by micheleriva — APPROVED** [review]

**Comment by thomscoder** [comment]
Oh perfect! 💯 
I was looking to solve the search plugin (i really cannot explain why 12 hours ago it was working and now even checking out to yesterday commits it does not anymore lol).
I'll open a issue (on that repo) for a head up asap. 
Thanksss

**Pull request merged**
