### PR TITLE
fixing the typo on simple-structures branch

### PR DESCRIPTION
**Pull request by Frenzarectah**
referring to issue #50

### CODE REVIEW

**Comment by mateonunez** [comment]
Thank you so much for your PR @Frenzarectah! 

Remember to commit your changes with `yarn|npm|pnpm` commit (I'm fixing commit messages right now). Lyra follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) as a standard for commit messages

**Comment by micheleriva** [comment]
@Frenzarectah also consider that this benchmark table gets generated on every commit. You should fix the script that generates the table, not the final result

**Comment by Frenzarectah** [comment]
thank you for the advices @micheleriva and @mateonunez ! 
I hope the next pull request will be ok.

**Comment by micheleriva** [comment]
You can edit this PR directly 🙂

**Pull request closed without merging**
