### PR TITLE
docs: add inline documentation

### PR DESCRIPTION
**Pull request by iShibi**
I have added docs only for the four major functions. Once the writing style gets a green flag I would be happy to document all the other stuff.

### CODE REVIEW

**Review by RafaelGSS — COMMENTED** [review]
I believe the inline documentation is useful just for the methods exported by this library. Internal methods should have their naming clear enough

**Comment by iShibi** [comment]
By other stuff I meant the `interfaces`. Doing so would allow the editor to show what a particular field in an object parameter does.

**Review by RafaelGSS — COMMENTED** [review]
Including `SearchResult` would be great, yeah.

**Review by RafaelGSS — COMMENTED** [review]
Most of the inline documentation is pretty redundant to me. Example:
```ts
export interface Lyra<S extends PropertiesSchema> extends Data<S> {
  /**
   * The default language analyzer in use.
   */
  defaultLanguage: Language;
  /**
   * The structure of documents stored in the database.
   */
  schema: S;
  edge: boolean;
}
```

You don't need to add inline documentation to everything, just mention unclear fields. For instance: 

```ts
/**
   * The maximum [levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance)
   * between the term and the searchable property.
   */
  tolerance?: number;
```

is a great addition. As said previously, I'd keep just the inline doc for exported functions + unclear fields (`tolerance`)

**Review by RafaelGSS — APPROVED** [review]

**Pull request merged**
